### PR TITLE
solution for VirtualHost and .htaccess redirection

### PR DESCRIPTION
**Pull request by emibia**
Hi Christoph, I've made some changes for make working the examples on my system with virtual hosts, .htaccess and zend lib.
Can you try if working?

### CODE REVIEW

**Comment by cadorn** [comment]
Sorry about the delayed reply.

What is the URL to the root of the example application?

The example application must sit at the root of the hostname.

**Comment by emibia** [comment]
now it's all relative to the URL exploded from $_SERVER['PHP_SELF']

**Comment by cadorn** [comment]
I realize that but I need to know what your original issue was as the entire example app only works when it sits at the root of the hostname for several reasons other than just the URL links.

**Comment by emibia** [comment]
the issue were that in the example frame doesn't load the code like presented an user in mailing list

**Comment by cadorn** [comment]
What is the URL to the root of the example application?

**Pull request closed without merging**
